<?php
namespace app\modules\apiv1\models;


class Post extends \app\models\Post
{

    public function fields()
    {
        return ['id','title','body','created_by','comments']; // TODO: Change the autogenerated stub
    }


    public function extraFields()
    {
        return ['created_at','updated_at','created_by','updated_by']; // TODO: Change the autogenerated stub
    }

}
