<?php
namespace app\modules\apiv1\models;


use app\models\Categoria;
use app\models\PostCategoria;
use yii\data\ActiveDataProvider;

class Post extends \app\models\Post
{

    public function fields()
    {
        return ['id','title','body','categorias']; // TODO: Change the autogenerated stub
    }

    public function getCategorias(){
        return $this->hasMany(Categoria::class,['id_categoria'=>'categoria_id'])
            ->viaTable(PostCategoria::tableName(),['post_id'=>'id']);
    }


    public function extraFields()
    {
        return ['comments','created_at','updated_at','created_by','updated_by']; // TODO: Change the autogenerated stub
    }

    public function search($params)
    {
        $query = $this->find();
//        $query->joinWith('comments');

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

//        $this->load($params,null);
        $this->setAttributes($params,false);
//        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
//            return $dataProvider;
//        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'created_by' => $this->created_by,
            'updated_by' => $this->updated_by,
        ]);

        $query->andFilterWhere(['like', 'title', $this->title])
            ->andFilterWhere(['like', 'body', $this->body]);

        return $dataProvider;
    }

}
